### ISSUE TITLE
Incorrect type for several instances

### ISSUE THREAD

**Issue by olinux** [HumanBrainProject/openMINDS_instances#10]
There are incorrect types for several instances for the technique section. Example:

https://github.com/HumanBrainProject/openMINDS_instances/blob/497ab21fd59138d75b5a746ee261e5a81fc60805/instances/technique/3DPolarizedLightImaging.jsonld#L3

It should be https://openminds.ebrains.eu/controlledTerms/Technique instead...

**Comment by lzehl** [comment]
Oh ha! I'll check and correct them

**Comment by lzehl** [comment]
@olinux any other errors discovered or can we close this now?

**Comment by lzehl** [comment]
solved in current version
