### ISSUE TITLE
Add data storage units

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_instances#20]
- bit (b)
- byte (B)
- kilobyte (KB)
- megabyte (MB) 
- gigabyte (GB)
- terabyte (TB)
- petabyte (PB)
- exabyte (EB)
- zettabyte (ZB)
- yottabyte (YB)

@olinux and @lzehl, more? less?

**Comment by lzehl** [comment]
From my point this is already more than enough. I would be also fine fixing one unit for file sizes (e.g., byte).
@olinux what is your impression?

**Comment by olinux** [comment]
I do agree - this should be way more than sufficient - for now we're going to use bytes only since this is the representation format we get from the SWIFT API.

**Comment by lzehl** [comment]
@olinux that means @UlrikeS91 should go ahead and register the units? For now I would only register everything between bit and terabyte I think

**Comment by olinux** [comment]
Yes, I think this is fine - as soon as we have use cases for the larger ones, we can still add them. I think it makes sense to have not only bytes to express imprecision (e.g. you might not know the exact byte size but a rounded GB information) -> this could then be reflected properly. We can think about it how we can simplify the interpretation on the client side
